# Arquitecturas Especializadas

### Profesor: Juan Mario Haut Hurtado
### 4º Ingeniería en Informática en Ingeniería de Computadores
__________________________________________________________________

# Torch and Numpy

Más información en: http://pytorch.org/docs/torch.html#math-operations

Importamos las librerías necesarias

In [1]:
import torch
import numpy as np

In [2]:
# Creación de numpy
dato_numpy = np.array([a for a in range(10)])
# convertimos el vector de 10 a una matriz de 2x5
dato_numpy = dato_numpy.reshape(2,5)
# Convertir numpy a tensores de Torch
dato_torch = torch.from_numpy(dato_numpy)
# Convertir tensor Torch a numpy array
tensor2array = dato_torch.numpy()
print('\nnumpy array:', dato_numpy, '\ntorch tensor:', dato_torch, '\ntensor to array:', tensor2array)


numpy array: [[0 1 2 3 4]
 [5 6 7 8 9]] 
torch tensor: tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]) 
tensor to array: [[0 1 2 3 4]
 [5 6 7 8 9]]


In [3]:
# Valor absoluto
data = [-1, -2, 1, 2]
tensor = torch.FloatTensor(data)  # Conversión a float (no es double)
print(
    '\nabs',
    '\nnumpy: ', np.abs(data),
    '\ntorch: ', torch.abs(tensor)
)


abs 
numpy:  [1 2 1 2] 
torch:  tensor([1., 2., 1., 2.])


In [ ]:
print(tensor)
print(tensor.abs())

tensor([-1., -2.,  1.,  2.])
tensor([1., 2., 1., 2.])


In [ ]:
# Coseno
print(
    '\ncos',
    '\nnumpy: ', np.cos(data),
    '\ntorch: ', torch.cos(tensor)
)


cos 
numpy:  [ 0.54030231 -0.41614684  0.54030231 -0.41614684] 
torch:  tensor([ 0.5403, -0.4161,  0.5403, -0.4161])


In [ ]:
tensor.sigmoid()

tensor([0.2689, 0.1192, 0.7311, 0.8808])

In [ ]:
tensor.exp()

tensor([0.3679, 0.1353, 2.7183, 7.3891])

In [ ]:
# Media
print(
    '\nMedia',
    '\nnumpy: ', np.average(tensor),
    '\ntorch: ', torch.mean(tensor)
)


Media 
numpy:  0.0 
torch:  tensor(0.)


In [4]:
# Multiplicación de matrices
data = np.array([[1,2], [3,4]])
tensor = torch.FloatTensor(data)  # Conversión a float (32bits)
# Método correcto
print(
    '\nMultiplicación de Matrices (matmul)',
    '\nnumpy: ', np.matmul(data, data),      # [[7, 10], [15, 22]]
    '\nnumpy: ', data @ data,                # [[7, 10], [15, 22]]
    '\ntorch: ', torch.mm(tensor, tensor),   # [[7, 10], [15, 22]]
    '\ntorch: ', tensor @ tensor             # [[7, 10], [15, 22]]
)

print("--------------------------------------------------")


# Método incorrecto: Esto es multiplicar elemento a elemento
print(
    '\nMultiplicación de Matrices (matmul)',
    '\nnumpy: ', np.multiply(data, data),
    '\nnumpy: ', data*data,
    '\ntorch: ', torch.mul(tensor, tensor),
    '\ntorch: ', tensor*tensor
)

print("--------------------------------------------------")


Multiplicación de Matrices (matmul) 
numpy:  [[ 7 10]
 [15 22]] 
numpy:  [[ 7 10]
 [15 22]] 
torch:  tensor([[ 7., 10.],
        [15., 22.]]) 
torch:  tensor([[ 7., 10.],
        [15., 22.]])
--------------------------------------------------

Multiplicación de Matrices (matmul) 
numpy:  [[ 1  4]
 [ 9 16]] 
numpy:  [[ 1  4]
 [ 9 16]] 
torch:  tensor([[ 1.,  4.],
        [ 9., 16.]]) 
torch:  tensor([[ 1.,  4.],
        [ 9., 16.]])
--------------------------------------------------


Muy importante: Multiplicar matrices no es multiplicarlas elemento a elemento.